"""change table

Revision ID: 73e3d23e33c5
Revises: e9d84e78012c
Create Date: 2025-03-13 18:03:09.678736

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73e3d23e33c5"
down_revision: Union[str, None] = "e9d84e78012c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_username", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_users_username", "users", ["username"])
    # ### end Alembic commands ###
