"""

Revision ID: f38a29707654
Revises: f07cef0007e0
Create Date: 2025-03-14 00:30:55.260856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f38a29707654"
down_revision: Union[str, None] = "f07cef0007e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_wallets_user_id_users", "wallets", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_wallets_user_id_users"),
        "wallets",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_wallets_user_id_users"), "wallets", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_wallets_user_id_users", "wallets", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
