"""

Revision ID: 024d73a8edfc
Revises: f2c79532cf81
Create Date: 2025-03-14 14:29:17.223753

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "024d73a8edfc"
down_revision: Union[str, None] = "f2c79532cf81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_users_username"), "users", ["username"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_username"), "users", type_="unique")
    # ### end Alembic commands ###
