services:
  redis:
    container_name: redis

    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - monitoring 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    container_name: db

    image: postgres
    environment:
      POSTGRES_USER: clanzu
      POSTGRES_PASSWORD: clanzu_pass
      POSTGRES_DB: clanzu_db
    ports:
      - "5432:5432"
    networks:
      - monitoring 

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clanzu -d clanzu_db"]
      interval: 5s
      timeout: 5s
      retries: 5


  web:
    image: web
    container_name: web
    build: .
    command: uvicorn main:main_app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - src/.env

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy 
      celery:
        condition: service_healthy 
    networks:
      - monitoring
      
  
  celery:
    container_name: celery
    volumes:
      - .:/app
    build: .
    working_dir: /app/src
    command: celery -A celery_app worker --beat --loglevel=info
    environment:
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      redis:
        condition: service_healthy 
    # user: "1000:1000"
    networks:
      - monitoring 
    healthcheck:
      test: ["CMD", "celery", "-A", "celery_app", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
    # restart: always

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
      

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring

volumes:
  grafana_data:
  postgres_data:
  redis_data:

networks:
  monitoring: