global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: "fastapi"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["web:8000"]  # Use Docker service name ("web" from compose file)
