services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres
    environment:
      POSTGRES_USER: clanzu
      POSTGRES_PASSWORD: clanzu_pass
      POSTGRES_DB: clanzu_db
    ports:
      - "5432:5432"


  web:
    build: .
    command: uvicorn main:main_app --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  
  celery-worker:
    volumes:
      - .:/app
    build: .
    command: celery -A celery_app worker --beat --loglevel=info
    environment:
      # PYTHONPATH: "/app"  # Critical for module resolution
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - redis
    user: "1000:1000"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"

volumes:
  postgres_data:
  redis_data: